{% set version = "1.6.1" %}

package:
    name: spefile
    version: {{ version }}

source:
    path: src

build:
    number: 0
    noarch: python
    script: "{{ PYTHON }} -m pip install --no-deps -vv ."

requirements:
    host:
        - pip
        - python
        - setuptools

    run:
        - python >=3
        - numpy

test:
    imports:
        - spefile

about:
    # Long term goal is to have the src/ folder in this recipe as a stand-alone
    # project on github.
    home: https://pythonhosted.org/pyspec/
    license: GPL-3.0-or-later
    license_file: LICENSE
    summary: >
        Reader for SPE files part of pyspec a set of python routines for data
        analysis of x-ray scattering experiments

extra:
    recipe-maintainers:
        - dgursoy
        - decarlof
        - ericdill
        - licode
        - ravescovi
        - tacaswell
